export type Category = {
  id: string;
  label: string;
  emoji: string;
};

export const CATEGORIES: Category[] = [
  { id: "normal",   label: "Normal",   emoji: "🌿" },
  { id: "romantic", label: "Romantic", emoji: "💕" },
  { id: "flirty",   label: "Flirty",   emoji: "😘" },
  { id: "funny",    label: "Funny",    emoji: "🤣" },
  { id: "adult",    label: "Adult",    emoji: "🍷" },
  { id: "kidish",   label: "Kid-ish",  emoji: "🧸" },
  { id: "nasty",    label: "Nasty",    emoji: "🌶️" },
];

export const PROMPTS: Record<string, { truths: string[]; dares: string[] }> = {
  normal: {
    truths: [
      "What is your favorite memory of us?",
      "What's a habit of mine you find endearing?",
      "When did you first know you loved me?",
      "What's something you've always wanted to try together?",
      "What's the most attractive quality about me?",
      "What's a small thing I do that makes you smile?",
      "What's one thing you wish we did more often?",
      "What's a secret talent you have?",
      "What's your favorite way to spend a lazy Sunday with me?",
      "What's the best advice you've ever received about relationships?",
      "What's a dream you've never told anyone?",
      "What's the kindest thing I've ever done for you?",
      "What's something you admire about how I handle hard days?",
      "What's your love language and do I speak it well?",
      "What's something you want to experience with me before we're old?",
    ],
    dares: [
      "Give me a 10-second shoulder massage.",
      "Sing the chorus of a love song to me.",
      "Tell me something you appreciate about me that you've never said aloud.",
      "Imitate my laugh.",
      "Hold my hand and look into my eyes for 20 seconds.",
      "Say something sweet in a funny accent.",
      "Text a mutual friend a compliment about our relationship.",
      "Draw a quick portrait of me in the air.",
      "Do your best impression of me waking up.",
      "Name three things you love about me without repeating yourself.",
    ],
  },
  romantic: {
    truths: [
      "What's the most romantic thing I've ever done for you?",
      "What's your ideal date night?",
      "What song makes you think of us?",
      "What's a promise you want to make to me?",
      "Where would you want to go for our dream vacation?",
      "What's your favorite thing about being with me?",
      "When do you feel most loved by me?",
      "What's a small gesture that means a lot to you?",
      "What's a memory that still gives you butterflies?",
      "What's one thing you'd like us to do every year?",
      "What's the moment you knew I was different?",
      "What does home feel like to you and am I part of it?",
      "What's a romantic cliché you secretly want us to do?",
      "What would your ideal anniversary look like?",
      "What's a love letter you'd write me but haven't yet?",
    ],
    dares: [
      "Write me a two-line poem right now.",
      "Slow dance with me for 30 seconds.",
      "Tell me three things you love about me.",
      "Give me a forehead kiss.",
      "Hold both my hands and say something sweet.",
      "Plan a surprise date idea out loud.",
      "Give me a compliment starting with 'I love the way you...'",
      "Recreate how you think our first kiss felt.",
      "Look into my eyes for 30 seconds without talking.",
      "Text me a love song you want to dedicate to me.",
    ],
  },
  flirty: {
    truths: [
      "What's your favorite pickup line?",
      "What's the most attractive outfit I own?",
      "What's something I do that's a total turn-on?",
      "What's a flirty text you'd send me if we just met?",
      "What's your signature move when flirting?",
      "What's a compliment you've received that made you blush?",
      "What part of my personality do you find sexy?",
      "What's something you find cute when I do it?",
      "What's a cheesy line you secretly like?",
      "What's a physical feature of mine you can't resist?",
      "What's something I do without realizing that drives you wild?",
      "What's your go-to move to get my attention?",
      "When was the last time I made your heart skip?",
      "What's the most attractive thing I've said to you?",
      "If you could describe my energy in one word, what would it be?",
    ],
    dares: [
      "Say something seductive in a language I don't speak.",
      "Give me your best 'come hither' look.",
      "Whisper a pickup line in my ear.",
      "Tell me a cheesy compliment with a straight face.",
      "Use a pet name you've never used before.",
      "Try to make me blush.",
      "Give me a wink that would make anyone swoon.",
      "Trace your finger slowly down my arm.",
      "Do a little shimmy or playful dance move.",
      "Imitate a flirtatious movie scene.",
    ],
  },
  funny: {
    truths: [
      "What's the funniest thing that ever happened to us?",
      "What's a joke that always makes you laugh?",
      "What's the most embarrassing thing you've done in public?",
      "What's a ridiculous fear you have?",
      "What's the worst fashion trend you followed?",
      "What's the funniest autocorrect fail you've had?",
      "What's a weird food combination you enjoy?",
      "What's the most awkward date you've been on (before me)?",
      "What's a movie that makes you cry laughing?",
      "What's the most bizarre dream you've had about me?",
      "What would your villain name be and what's your evil plan?",
      "What animal do I remind you of and why?",
      "What's the weirdest thing you've Googled recently?",
      "What's a habit of yours that would horrify your parents?",
      "What's a nickname you secretly gave me in your head?",
    ],
    dares: [
      "Do your best celebrity impression.",
      "Tell a 'dad joke' and try not to laugh.",
      "Do an interpretive dance of how you feel right now.",
      "Make up a rap about our relationship on the spot.",
      "Talk without moving your lips for 20 seconds.",
      "Try to lick your elbow.",
      "Do a dramatic reading of a grocery list.",
      "Make the sound of an animal I choose.",
      "Try to make me laugh using only facial expressions.",
      "Walk across the room like a runway model.",
    ],
  },
  adult: {
    truths: [
      "What's a fantasy you've never told me about?",
      "What turns you on that I might not realize?",
      "What's your favorite part of my body?",
      "Have you ever had a dream about me that was spicy?",
      "When do you feel most attracted to me?",
      "What's something you'd like me to whisper in your ear?",
      "What's a movie scene you found unexpectedly arousing?",
      "What's a secret desire you're shy to admit?",
      "What's the most adventurous thing you'd want to try?",
      "What's something you want more of in our relationship?",
      "What time of day are you most in the mood?",
      "What's something I do that makes you feel wanted?",
      "What's a fantasy location you'd want to be intimate in?",
      "What song would be on your 'mood' playlist?",
      "What's something you want to ask me but haven't dared?",
      "Have you ever accidentally sent a sext to the wrong person?",
      "Who would you like to sext right now?",
      "...Why don't you do it?",
      "Who in your contact list would you most want us to have a threesome with?",
      "What's your favorite body part of mine?",
      "What's your biggest roleplay fantasy?",
      "Who was the first person you had a crush on?",
      "Where's the craziest place you want to hook up with me?",
      "Have you ever had a sex dream about me?",
      "What's the weirdest thing anyone has ever said to you during sex?",
      "What's the weirdest thing you've ever said to anyone during sex?",
      "Would you like to make a sex tape with me?",
      "Would you rather do a pole dance or a striptease?",
      "What part of my body would you like to lick right now?",
      "How many one-night stands have you had?",
      "Have you ever put a sexy selfie on social media?",
      "What's your biggest turn-on when you think about me?",
      "If I gave you whipped cream right now, what would you do with it?",
      "What's the dirtiest thing you'd like me to do to you?",
      "Do you think my best friend is hot?",
      "How soon after meeting someone have you slept with them for the first time?",
      "Have you ever broken a bed during sex?",
      "Would you rather only sext for the rest of your life, or only have phone sex?",
      "What common turn-off really turns you on?",
      "When did you first realize you were attracted to me?",
      "Have you ever faked an orgasm?",
      "Have you ever faked an orgasm... with me?",
      "Have you ever slept with a co-worker?",
      "Would you want a threesome with me and my best friend?",
      "Would you want a threesome with me and your best friend?",
      "What's the craziest thing you've done in a sex dream?",
      "Have you ever been turned on at work?",
      "...What happened?",
      "...And what did you do about it?",
      "Have you ever been to a sex club?",
      "...Would you like to?",
      "When was the last time I turned you on?",
      "Is there a sex toy you'd like to try on me?",
      "Have you ever injured yourself during sex?",
      "Have you ever had sex in a public place?",
      "When was the last time you touched yourself?",
      "...What were you thinking about?",
      "Would you rather be dominant or submissive?",
      "Have you ever fallen asleep during sex?",
      "Have you ever been to a strip club?",
      "Has anyone ever walked in on you during sex?",
      "Would you rather only use your tongue or only use your fingers?",
      "What's your favorite thing about my body?",
      "Would you rather only have morning sex for the rest of your life, or never have morning sex again?",
      "What was your first sexual fantasy?",
      "Have you ever tried swinging or partner swapping?",
      "...Would you like to?",
      "Which celebrity would you like to see me make out with?",
      "Would you like to watch me make out with my best friend?",
      "Would you like to watch me make out with your best friend?",
      "How would you describe my sexual personality?",
      "What's your favorite memory of us having sex?",
      "...Is there anything that could have made it even better?",
      "What's the sexiest gift I could give you?",
      "What's the sexiest gift you'd like to give me?",
      "Have you ever kept a relationship secret?",
      "What's your most romantic memory of me?",
      "Have you ever experimented with people of different genders?",
    ],
    dares: [
      "Whisper something suggestive in my ear.",
      "Give me a sensual neck kiss.",
      "Describe what you'd do if we were alone right now.",
      "Send me a flirty text even though we're in the same room.",
      "Tell me a secret fantasy in three words.",
      "Give me a back scratch with your nails.",
      "Slow dance with me for 30 seconds with no music.",
      "Put your hand on my knee and leave it there.",
      "Say the most seductive thing you can think of with a straight face.",
      "Give me a kiss somewhere surprising.",
    ],
  },
  kidish: {
    truths: [
      "What was your favorite childhood TV show?",
      "What's the silliest thing you believed as a kid?",
      "What's a game you loved playing as a child?",
      "What was your favorite snack after school?",
      "What's a funny childhood memory?",
      "What's a toy you wished you still had?",
      "What's the most embarrassing thing you did as a kid?",
      "What's a cartoon character you had a crush on?",
      "What's a silly fear you had growing up?",
      "What's a family tradition from your childhood?",
      "What's the worst thing you ever blamed a sibling for?",
      "What's a made-up word you used as a child?",
      "What did you want to be when you grew up?",
      "What's the first thing you ever saved up money to buy?",
      "What's a song that takes you straight back to childhood?",
    ],
    dares: [
      "Do an impression of a cartoon character.",
      "Tell a joke a 7-year-old would love.",
      "Make a funny face and hold it for 10 seconds.",
      "Sing a nursery rhyme with exaggerated emotion.",
      "Do a silly walk across the room.",
      "Pretend you're a dinosaur for 20 seconds.",
      "Talk in a baby voice for one full minute.",
      "Balance a spoon on your nose.",
      "Draw a simple animal with your eyes closed.",
      "Imitate a famous children's show host.",
    ],
  },
  nasty: {
    truths: [
      "What's a roleplay scenario you'd enjoy?",
      "What's the naughtiest thought you've had today?",
      "Where's the riskiest place you'd want to be intimate?",
      "What's a body part of mine you fantasize about?",
      "What's the kinkiest thing you've ever done?",
      "What's a dirty word that turns you on?",
      "What's something you want to try that you saw in a movie?",
      "What's your favorite position?",
      "What would you want me to do if I woke you up in the middle of the night?",
      "What's the boldest thing you've ever said to someone you were attracted to?",
      "What's something you find irresistibly attractive that most people wouldn't expect?",
      "How long is the longest you could go without kissing me?",
      "What's the most daring thing you'd do in public?",
      "What would the title of a steamy book about us be?",
      "What's something you want but feel embarrassed asking for?",
    ],
    dares: [
      "Whisper the dirtiest word you can think of.",
      "Bite my lip gently.",
      "Tell me what you want me to do to you later.",
      "Describe in detail a fantasy involving us.",
      "Kiss me somewhere unexpected.",
      "Put your hand on my thigh and leave it there.",
      "Send me a suggestive emoji string describing your mood.",
      "Tell me your mood in three spicy words.",
      "Give me a hickey — or pretend to.",
      "Act out a scene from your favorite romantic movie.",
    ],
  },
};